<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AgenciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 代理机构表种子数据
     */
    public function run()
    {
        $agencies = [
            [
                'sort' => 1,
                'agency_code' => 'BJ001',
                'agency_name_cn' => '北京睿道知识产权代理有限公司',
                'agency_name_en' => 'Beijing Readow IP Agency Co., Ltd.',
                'country' => '中国',
                'social_credit_code' => '91110105MA01ABCD12',
                'create_time' => '2020-01-01',
                'account' => 'bj001@readow.com',
                'password' => bcrypt('123456'),
                'province' => '北京市',
                'city' => '朝阳区',
                'province_en' => 'Beijing',
                'city_en' => 'Chaoyang',
                'address_cn' => '朝阳区建国路88号SOHO现代城A座2001室',
                'address_en' => 'Room 2001, Tower A, SOHO Modern City, No.88 Jianguo Road, Chaoyang District',
                'postcode' => '100022',
                'manager' => '张经理',
                'contact' => '李联络',
                'modifier' => '系统管理员',
                'agent_type' => '专利',
                'is_valid' => true,
                'is_supplier' => true,
                'requirements' => '专业的专利申请和维护服务，具备丰富的国内外专利申请经验',
                'remark' => '优质合作伙伴，专利申请成功率高，服务质量优秀',
                'creator' => '系统管理员',
                'creation_time' => Carbon::now(),
                'update_time' => Carbon::now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 2,
                'agency_code' => 'SH001',
                'agency_name_cn' => '上海华诚知识产权代理有限公司',
                'agency_name_en' => 'Shanghai Huacheng IP Agency Co., Ltd.',
                'country' => '中国',
                'social_credit_code' => '91310115MA02EFGH34',
                'create_time' => '2018-06-15',
                'account' => 'sh001@huacheng.com',
                'password' => bcrypt('123456'),
                'province' => '上海市',
                'city' => '浦东新区',
                'province_en' => 'Shanghai',
                'city_en' => 'Pudong',
                'address_cn' => '浦东新区陆家嘴环路1000号恒生银行大厦15楼',
                'address_en' => '15F, Hang Seng Bank Tower, No.1000 Lujiazui Ring Road, Pudong New Area',
                'postcode' => '200120',
                'manager' => '王经理',
                'contact' => '赵联络',
                'modifier' => '系统管理员',
                'agent_type' => '商标',
                'is_valid' => true,
                'is_supplier' => false,
                'requirements' => '商标注册和维护服务，熟悉国内外商标法律法规',
                'remark' => '长期合作伙伴，商标业务专业，服务响应及时',
                'creator' => '系统管理员',
                'creation_time' => Carbon::now(),
                'update_time' => Carbon::now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 3,
                'agency_code' => 'GZ001',
                'agency_name_cn' => '广州德恒知识产权代理有限公司',
                'agency_name_en' => 'Guangzhou Deheng IP Agency Co., Ltd.',
                'country' => '中国',
                'social_credit_code' => '91440101MA03IJKL56',
                'create_time' => '2019-03-20',
                'account' => 'gz001@deheng.com',
                'password' => bcrypt('123456'),
                'province' => '广东省',
                'city' => '广州市',
                'province_en' => 'Guangdong',
                'city_en' => 'Guangzhou',
                'address_cn' => '天河区珠江新城花城大道85号高德置地春广场A座20楼',
                'address_en' => '20F, Tower A, Gao De Land Plaza, No.85 Huacheng Avenue, Zhujiang New Town, Tianhe District',
                'postcode' => '510623',
                'manager' => '陈经理',
                'contact' => '林联络',
                'modifier' => '系统管理员',
                'agent_type' => '版权',
                'is_valid' => true,
                'is_supplier' => true,
                'requirements' => '版权登记和保护服务，擅长软件著作权和作品著作权申请',
                'remark' => '新兴合作伙伴，版权业务专业，价格合理',
                'creator' => '系统管理员',
                'creation_time' => Carbon::now(),
                'update_time' => Carbon::now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 4,
                'agency_code' => 'SZ001',
                'agency_name_cn' => '深圳创新知识产权代理有限公司',
                'agency_name_en' => 'Shenzhen Innovation IP Agency Co., Ltd.',
                'country' => '中国',
                'social_credit_code' => '91440300MA04MNOP78',
                'create_time' => '2021-08-10',
                'account' => 'sz001@innovation.com',
                'password' => bcrypt('123456'),
                'province' => '广东省',
                'city' => '深圳市',
                'province_en' => 'Guangdong',
                'city_en' => 'Shenzhen',
                'address_cn' => '南山区科技园南区深圳湾科技生态园10栋A座',
                'address_en' => 'Tower A, Building 10, Shenzhen Bay Science & Technology Ecological Park, Nanshan District',
                'postcode' => '518057',
                'manager' => '刘经理',
                'contact' => '周联络',
                'modifier' => '系统管理员',
                'agent_type' => '专利',
                'is_valid' => true,
                'is_supplier' => true,
                'requirements' => '高新技术专利申请，特别擅长电子信息技术领域',
                'remark' => '科技园区专业代理机构，技术理解能力强',
                'creator' => '系统管理员',
                'creation_time' => Carbon::now(),
                'update_time' => Carbon::now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 5,
                'agency_code' => 'US001',
                'agency_name_cn' => '美国专利代理公司',
                'agency_name_en' => 'US Patent Agency Inc.',
                'country' => '美国',
                'social_credit_code' => null,
                'create_time' => '2018-08-10',
                'account' => 'us001@uspatent.com',
                'password' => bcrypt('123456'),
                'province' => '加利福尼亚州',
                'city' => '硅谷',
                'province_en' => 'California',
                'city_en' => 'Silicon Valley',
                'address_cn' => '硅谷大道500号科技园区',
                'address_en' => 'No.500 Silicon Valley Blvd, Tech Park',
                'postcode' => '94000',
                'manager' => 'John Smith',
                'contact' => 'Mary Johnson',
                'modifier' => '系统管理员',
                'agent_type' => '专利',
                'is_valid' => true,
                'is_supplier' => false,
                'requirements' => '美国专利申请和维护，PCT国际申请',
                'remark' => '海外合作伙伴，美国专利申请专业，英文服务',
                'creator' => '系统管理员',
                'creation_time' => Carbon::now(),
                'update_time' => Carbon::now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        // 检查是否已有数据，避免重复插入
        if (DB::table('agencies')->count() == 0) {
            DB::table('agencies')->insert($agencies);
        }
    }
}
