<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Rap2hpoutre\FastExcel\Facades\FastExcel;

class ApplyTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 申请类型表种子数据
     */
    public function run()
    {
        
        DB::table('apply_types')->truncate();
        $time = '2025-01-01 00:00:00';
        $applyTypes = [
            [
                'country' => 'ALL',
                'case_type' => '专利',
                'business_type' => '发明专利',
                'apply_type_name' => '发明专利申请',
                'apply_type_code' => 'CN_INVENTION',
                'description' => '对产品、方法或者其改进所提出的新的技术方案',
                'status' => 1,
                'is_default' => 1,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => 'ALL',
                'case_type' => '专利',
                'business_type' => '实用新型专利',
                'apply_type_name' => '实用新型专利申请',
                'apply_type_code' => 'CN_UTILITY_MODEL',
                'description' => '对产品的形状、构造或者其结合所提出的适于实用的新的技术方案',
                'status' => 1,
                'is_default' => 0,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => '中国',
                'case_type' => '专利',
                'business_type' => '外观设计专利',
                'apply_type_name' => '外观设计专利申请',
                'apply_type_code' => 'CN_DESIGN',
                'description' => '对产品的形状、图案或者其结合以及色彩与形状、图案的结合所作出的富有美感并适于工业应用的新设计',
                'status' => 1,
                'is_default' => 0,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => '中国',
                'case_type' => '商标',
                'business_type' => '商标注册',
                'apply_type_name' => '商标注册申请',
                'apply_type_code' => 'CN_TRADEMARK',
                'description' => '商标注册申请，获得商标专用权',
                'status' => 1,
                'is_default' => 1,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => '中国',
                'case_type' => '版权',
                'business_type' => '软件著作权',
                'apply_type_name' => '软件著作权登记',
                'apply_type_code' => 'CN_SOFTWARE_COPYRIGHT',
                'description' => '计算机软件著作权登记',
                'status' => 1,
                'is_default' => 1,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => '中国',
                'case_type' => '版权',
                'business_type' => '作品著作权',
                'apply_type_name' => '作品著作权登记',
                'apply_type_code' => 'CN_WORK_COPYRIGHT',
                'description' => '文学、艺术和科学作品著作权登记',
                'status' => 1,
                'is_default' => 0,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => '国际',
                'case_type' => '专利',
                'business_type' => 'PCT申请',
                'apply_type_name' => 'PCT国际专利申请',
                'apply_type_code' => 'PCT_INTERNATIONAL',
                'description' => '专利合作条约(PCT)国际专利申请',
                'status' => 1,
                'is_default' => 0,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => '美国',
                'case_type' => '专利',
                'business_type' => '美国专利',
                'apply_type_name' => '美国发明专利申请',
                'apply_type_code' => 'US_UTILITY_PATENT',
                'description' => '美国发明专利(Utility Patent)申请',
                'status' => 1,
                'is_default' => 0,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => '欧洲',
                'case_type' => '专利',
                'business_type' => '欧洲专利',
                'apply_type_name' => '欧洲专利申请',
                'apply_type_code' => 'EP_PATENT_APPLICATION',
                'description' => '欧洲专利局(EPO)专利申请',
                'status' => 1,
                'is_default' => 0,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => '日本',
                'case_type' => '专利',
                'business_type' => '日本专利',
                'apply_type_name' => '日本专利申请',
                'apply_type_code' => 'JP_PATENT_APPLICATION',
                'description' => '日本特许厅专利申请',
                'status' => 1,
                'is_default' => 0,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // 科技服务相关申请类型
            [
                'country' => '中国',
                'case_type' => '科服',
                'business_type' => '企业认定',
                'apply_type_name' => '高新技术企业认定',
                'apply_type_code' => 'HIGH_TECH_ENTERPRISE',
                'description' => '国家高新技术企业认定申请',
                'status' => 1,
                'is_default' => 0,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => '中国',
                'case_type' => '科服',
                'business_type' => '科技服务',
                'apply_type_name' => '科技成果转化',
                'apply_type_code' => 'TECH_ACHIEVEMENT_TRANSFER',
                'description' => '科技成果转化项目申请',
                'status' => 1,
                'is_default' => 0,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => '中国',
                'case_type' => '科服',
                'business_type' => '科技服务',
                'apply_type_name' => '技术转移服务',
                'apply_type_code' => 'TECH_TRANSFER_SERVICE',
                'description' => '技术转移服务平台建设',
                'status' => 1,
                'is_default' => 0,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => '中国',
                'case_type' => '科服',
                'business_type' => '企业认定',
                'apply_type_name' => '科技型中小企业认定',
                'apply_type_code' => 'TECH_SME_CERTIFICATION',
                'description' => '科技型中小企业认定申请',
                'status' => 1,
                'is_default' => 0,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => '中国',
                'case_type' => '科服',
                'business_type' => '认证申报',
                'apply_type_name' => '知识产权贯标认证',
                'apply_type_code' => 'IP_MANAGEMENT_CERTIFICATION',
                'description' => '企业知识产权管理规范认证',
                'status' => 1,
                'is_default' => 0,
                'is_valid' => 1,
                'update_user' => '系统管理员',
                'sort_order' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];
        DB::table('apply_types')->insert($applyTypes);
    }
}
