<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 国家表种子数据
     */
    public function run()
    {
        $countries = [
            [
                'name' => '中国',
                'code' => 'CN',
                'description' => '中华人民共和国',
                'status' => 1,
                'sort_order' => 1,
                'country_name' => '中国',
                'country_name_en' => 'China',
                'country_code' => 'CN',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '美国',
                'code' => 'US',
                'description' => '美利坚合众国',
                'status' => 1,
                'sort_order' => 2,
                'country_name' => '美国',
                'country_name_en' => 'United States',
                'country_code' => 'US',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '日本',
                'code' => 'JP',
                'description' => '日本国',
                'status' => 1,
                'sort_order' => 3,
                'country_name' => '日本',
                'country_name_en' => 'Japan',
                'country_code' => 'JP',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '德国',
                'code' => 'DE',
                'description' => '德意志联邦共和国',
                'status' => 1,
                'sort_order' => 4,
                'country_name' => '德国',
                'country_name_en' => 'Germany',
                'country_code' => 'DE',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '英国',
                'code' => 'GB',
                'description' => '大不列颠及北爱尔兰联合王国',
                'status' => 1,
                'sort_order' => 5,
                'country_name' => '英国',
                'country_name_en' => 'United Kingdom',
                'country_code' => 'GB',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '法国',
                'code' => 'FR',
                'description' => '法兰西共和国',
                'status' => 1,
                'sort_order' => 6,
                'country_name' => '法国',
                'country_name_en' => 'France',
                'country_code' => 'FR',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '韩国',
                'code' => 'KR',
                'description' => '大韩民国',
                'status' => 1,
                'sort_order' => 7,
                'country_name' => '韩国',
                'country_name_en' => 'South Korea',
                'country_code' => 'KR',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '加拿大',
                'code' => 'CA',
                'description' => '加拿大',
                'status' => 1,
                'sort_order' => 8,
                'country_name' => '加拿大',
                'country_name_en' => 'Canada',
                'country_code' => 'CA',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '澳大利亚',
                'code' => 'AU',
                'description' => '澳大利亚联邦',
                'status' => 1,
                'sort_order' => 9,
                'country_name' => '澳大利亚',
                'country_name_en' => 'Australia',
                'country_code' => 'AU',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '意大利',
                'code' => 'IT',
                'description' => '意大利共和国',
                'status' => 1,
                'sort_order' => 10,
                'country_name' => '意大利',
                'country_name_en' => 'Italy',
                'country_code' => 'IT',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '荷兰',
                'code' => 'NL',
                'description' => '荷兰王国',
                'status' => 1,
                'sort_order' => 11,
                'country_name' => '荷兰',
                'country_name_en' => 'Netherlands',
                'country_code' => 'NL',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '瑞士',
                'code' => 'CH',
                'description' => '瑞士联邦',
                'status' => 1,
                'sort_order' => 12,
                'country_name' => '瑞士',
                'country_name_en' => 'Switzerland',
                'country_code' => 'CH',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '欧洲专利局',
                'code' => 'EP',
                'description' => '欧洲专利局',
                'status' => 1,
                'sort_order' => 13,
                'country_name' => '欧洲专利局',
                'country_name_en' => 'European Patent Office',
                'country_code' => 'EP',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'PCT国际申请',
                'code' => 'PCT',
                'description' => '专利合作条约国际申请',
                'status' => 1,
                'sort_order' => 14,
                'country_name' => 'PCT国际申请',
                'country_name_en' => 'PCT International Application',
                'country_code' => 'PCT',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '马德里国际商标',
                'code' => 'MADRID',
                'description' => '马德里国际商标注册',
                'status' => 1,
                'sort_order' => 15,
                'country_name' => '马德里国际商标',
                'country_name_en' => 'Madrid International Trademark',
                'country_code' => 'MADRID',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        // 检查是否已有数据，避免重复插入
        if (DB::table('countries')->count() == 0) {
            DB::table('countries')->insert($countries);
        }
    }
}
