<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CustomerContactsSeeder extends Seeder
{
    /**
     * 运行客户联系人数据种子
     *
     * @return void
     */
    public function run()
    {
        // 清空现有数据
        DB::table('customer_contacts')->truncate();

        $now = Carbon::now();

        // 创建示例联系人数据
        $contacts = [
            [
                'id' => 1,
                'customer_id' => 1,
                'contact_name' => '张经理',
                'contact_type' => 1,
                'contact_type_text' => '技术总监',
                'gender' => '男',
                'position' => '技术总监',
                'phone' => '13800138000',
                'telephone' => '021-88889999-8801',
                'email' => 'zhangsan@ruidao.com',
                'work_email' => 'zhangsan@ruidao.com',
                'wechat' => 'zhangsan_wx',
                'qq' => '123456789',
                'address' => '上海市浦东新区张江高科技园区博云路2号',
                'work_address' => '上海市浦东新区张江高科技园区博云路2号801室',
                'id_card' => '310115198501010001',
                'is_primary' => 1,
                'is_on_job' => true,
                'title' => '张总',
                'department' => '技术部',
                'business_staff' => '王销售',
                'status' => 1,
                'remarks' => '主要技术负责人，负责专利申请相关技术事务',
                'creator' => '系统管理员',
                'create_time' => '2024-01-01 10:00:00',
                'updater' => '',
                'update_time' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'customer_id' => 1,
                'contact_name' => '李助理',
                'contact_type' => 2,
                'contact_type_text' => '行政助理',
                'gender' => '女',
                'position' => '行政助理',
                'phone' => '13900139000',
                'telephone' => '021-88889999-8802',
                'email' => 'lisi@ruidao.com',
                'work_email' => 'lisi@ruidao.com',
                'wechat' => 'lisi_wx',
                'qq' => '987654321',
                'address' => '上海市浦东新区张江高科技园区博云路2号',
                'work_address' => '上海市浦东新区张江高科技园区博云路2号802室',
                'id_card' => '310115199001010002',
                'is_primary' => 0,
                'is_on_job' => true,
                'title' => '李助理',
                'department' => '行政部',
                'business_staff' => '王销售',
                'status' => 1,
                'remarks' => '负责日常行政事务和文件传递',
                'creator' => '系统管理员',
                'create_time' => '2024-01-02 11:00:00',
                'updater' => '',
                'update_time' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'customer_id' => 1,
                'contact_name' => '王财务',
                'contact_type' => 3,
                'contact_type_text' => '财务人员',
                'gender' => '女',
                'position' => '财务主管',
                'phone' => '13700137000',
                'telephone' => '021-88889999-8803',
                'email' => 'wangwu@ruidao.com',
                'work_email' => 'wangwu@ruidao.com',
                'wechat' => 'wangwu_wx',
                'qq' => '456789123',
                'address' => '上海市浦东新区张江高科技园区博云路2号',
                'work_address' => '上海市浦东新区张江高科技园区博云路2号803室',
                'id_card' => '310115198801010003',
                'is_primary' => 0,
                'is_on_job' => true,
                'title' => '王主管',
                'department' => '财务部',
                'business_staff' => '王销售',
                'status' => 1,
                'remarks' => '负责财务事务和发票开具',
                'creator' => '系统管理员',
                'create_time' => '2024-01-03 14:00:00',
                'updater' => '',
                'update_time' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 客户2的联系人
            [
                'id' => 4,
                'customer_id' => 2,
                'contact_name' => '陈总',
                'contact_type' => 1,
                'contact_type_text' => '决策人',
                'gender' => '男',
                'position' => '总经理',
                'phone' => '13600136000',
                'telephone' => '010-66668888-8801',
                'email' => 'chenzong@company2.com',
                'work_email' => 'chenzong@company2.com',
                'wechat' => 'chenzong_wx',
                'qq' => '111222333',
                'address' => '北京市朝阳区建国门外大街1号',
                'work_address' => '北京市朝阳区建国门外大街1号1001室',
                'id_card' => '110101197501010004',
                'is_primary' => 1,
                'is_on_job' => true,
                'title' => '陈总',
                'department' => '总经理办公室',
                'business_staff' => '李销售',
                'status' => 1,
                'remarks' => '公司决策人，负责重大事务决策',
                'creator' => '系统管理员',
                'create_time' => '2024-01-04 09:00:00',
                'updater' => '',
                'update_time' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'customer_id' => 2,
                'contact_name' => '刘工程师',
                'contact_type' => 2,
                'contact_type_text' => '技术人员',
                'gender' => '男',
                'position' => '高级工程师',
                'phone' => '13500135000',
                'telephone' => '010-66668888-8802',
                'email' => 'liugongchengshi@company2.com',
                'work_email' => 'liugongchengshi@company2.com',
                'wechat' => 'liugcs_wx',
                'qq' => '444555666',
                'address' => '北京市朝阳区建国门外大街1号',
                'work_address' => '北京市朝阳区建国门外大街1号1002室',
                'id_card' => '110101198201010005',
                'is_primary' => 0,
                'is_on_job' => true,
                'title' => '刘工',
                'department' => '研发部',
                'business_staff' => '李销售',
                'status' => 1,
                'remarks' => '负责技术研发和专利技术支持',
                'creator' => '系统管理员',
                'create_time' => '2024-01-05 10:30:00',
                'updater' => '',
                'update_time' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 客户3的联系人
            [
                'id' => 6,
                'customer_id' => 3,
                'contact_name' => '赵秘书',
                'contact_type' => 2,
                'contact_type_text' => '使用人',
                'gender' => '女',
                'position' => '总经理秘书',
                'phone' => '13400134000',
                'telephone' => '0755-77779999-8801',
                'email' => 'zhaomishu@company3.com',
                'work_email' => 'zhaomishu@company3.com',
                'wechat' => 'zhaoms_wx',
                'qq' => '777888999',
                'address' => '深圳市南山区科技园南区高新南一道1号',
                'work_address' => '深圳市南山区科技园南区高新南一道1号2001室',
                'id_card' => '440301199001010006',
                'is_primary' => 1,
                'is_on_job' => true,
                'title' => '赵秘书',
                'department' => '总经理办公室',
                'business_staff' => '张销售',
                'status' => 1,
                'remarks' => '负责总经理日程安排和对外联络',
                'creator' => '系统管理员',
                'create_time' => '2024-01-06 15:00:00',
                'updater' => '',
                'update_time' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'customer_id' => 3,
                'contact_name' => '孙采购',
                'contact_type' => 3,
                'contact_type_text' => '采购',
                'gender' => '男',
                'position' => '采购经理',
                'phone' => '13300133000',
                'telephone' => '0755-77779999-8802',
                'email' => 'suncaigou@company3.com',
                'work_email' => 'suncaigou@company3.com',
                'wechat' => 'suncg_wx',
                'qq' => '000111222',
                'address' => '深圳市南山区科技园南区高新南一道1号',
                'work_address' => '深圳市南山区科技园南区高新南一道1号2002室',
                'id_card' => '440301198501010007',
                'is_primary' => 0,
                'is_on_job' => true,
                'title' => '孙经理',
                'department' => '采购部',
                'business_staff' => '张销售',
                'status' => 1,
                'remarks' => '负责公司采购事务和供应商管理',
                'creator' => '系统管理员',
                'create_time' => '2024-01-07 16:30:00',
                'updater' => '',
                'update_time' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ];

        DB::table('customer_contacts')->insert($contacts);
        
        $this->command->info('客户联系人数据种子已成功植入！');
    }
}