<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class FeeConfigsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 费用配置表种子数据
     */
    public function run()
    {
        $feeConfigs = [
            [
                'sort' => 1,
                'case_type' => json_encode(['专利']),
                'business_type' => json_encode(['普通新申请']),
                'apply_type' => json_encode(['发明专利申请']),
                'country' => json_encode(['中国']),
                'fee_type' => '官费',
                'fee_name' => '发明专利申请费',
                'fee_name_en' => 'Invention Patent Application Fee',
                'currency' => 'CNY',
                'fee_code' => 'CN_INVENTION_APP_FEE',
                'base_fee' => 900.00,
                'small_entity_fee' => 135.00,
                'micro_entity_fee' => 90.00,
                'role' => json_encode(['申请人']),
                'use_stage' => json_encode(['新申请']),
                'fee_category' => '申请费',
                'additional_fee' => 0.00,
                'unit' => '元',
                'description' => '中国发明专利申请官费',
                'status' => 1,
                'is_required' => 1,
                'is_valid' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'sort_order' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 2,
                'case_type' => json_encode(['专利']),
                'business_type' => json_encode(['代缴年费案件']),
                'apply_type' => json_encode(['发明专利年费']),
                'country' => json_encode(['中国']),
                'fee_type' => '官费',
                'fee_name' => '发明专利年费',
                'fee_name_en' => 'Invention Patent Annual Fee',
                'currency' => 'CNY',
                'fee_code' => 'CN_INVENTION_ANNUAL_FEE',
                'base_fee' => 600.00,
                'small_entity_fee' => 90.00,
                'micro_entity_fee' => 60.00,
                'role' => json_encode(['申请人']),
                'use_stage' => json_encode(['复无年变续转']),
                'fee_category' => '年费',
                'additional_fee' => 0.00,
                'unit' => '元',
                'description' => '中国发明专利年费',
                'status' => 1,
                'is_required' => 1,
                'is_valid' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'sort_order' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 3,
                'case_type' => json_encode(['商标']),
                'business_type' => json_encode(['普通新申请']),
                'apply_type' => json_encode(['商标注册申请']),
                'country' => json_encode(['中国']),
                'fee_type' => '官费',
                'fee_name' => '商标注册申请费',
                'fee_name_en' => 'Trademark Registration Application Fee',
                'currency' => 'CNY',
                'fee_code' => 'CN_TRADEMARK_APP_FEE',
                'base_fee' => 300.00,
                'small_entity_fee' => 300.00,
                'micro_entity_fee' => 300.00,
                'role' => json_encode(['申请人']),
                'use_stage' => json_encode(['新申请']),
                'fee_category' => '申请费',
                'additional_fee' => 0.00,
                'unit' => '元',
                'description' => '中国商标注册申请官费',
                'status' => 1,
                'is_required' => 1,
                'is_valid' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'sort_order' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 4,
                'case_type' => json_encode(['版权']),
                'business_type' => json_encode(['普通新申请']),
                'apply_type' => json_encode(['作品登记申请']),
                'country' => json_encode(['中国']),
                'fee_type' => '官费',
                'fee_name' => '作品登记申请费',
                'fee_name_en' => 'Copyright Registration Application Fee',
                'currency' => 'CNY',
                'fee_code' => 'CN_COPYRIGHT_APP_FEE',
                'base_fee' => 200.00,
                'small_entity_fee' => 200.00,
                'micro_entity_fee' => 200.00,
                'role' => json_encode(['申请人']),
                'use_stage' => json_encode(['新申请']),
                'fee_category' => '申请费',
                'additional_fee' => 0.00,
                'unit' => '元',
                'description' => '中国作品登记申请官费',
                'status' => 1,
                'is_required' => 1,
                'is_valid' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'sort_order' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 5,
                'case_type' => json_encode(['专利']),
                'business_type' => json_encode(['普通新申请']),
                'apply_type' => json_encode(['实用新型专利申请']),
                'country' => json_encode(['中国']),
                'fee_type' => '官费',
                'fee_name' => '实用新型专利申请费',
                'fee_name_en' => 'Utility Model Patent Application Fee',
                'currency' => 'CNY',
                'fee_code' => 'CN_UTILITY_MODEL_APP_FEE',
                'base_fee' => 500.00,
                'small_entity_fee' => 75.00,
                'micro_entity_fee' => 50.00,
                'role' => json_encode(['申请人']),
                'use_stage' => json_encode(['新申请']),
                'fee_category' => '申请费',
                'additional_fee' => 0.00,
                'unit' => '元',
                'description' => '中国实用新型专利申请官费',
                'status' => 1,
                'is_required' => 1,
                'is_valid' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'sort_order' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 6,
                'case_type' => json_encode(['专利']),
                'business_type' => json_encode(['普通新申请']),
                'apply_type' => json_encode(['外观设计专利申请']),
                'country' => json_encode(['中国']),
                'fee_type' => '官费',
                'fee_name' => '外观设计专利申请费',
                'fee_name_en' => 'Design Patent Application Fee',
                'currency' => 'CNY',
                'fee_code' => 'CN_DESIGN_APP_FEE',
                'base_fee' => 500.00,
                'small_entity_fee' => 75.00,
                'micro_entity_fee' => 50.00,
                'role' => json_encode(['申请人']),
                'use_stage' => json_encode(['新申请']),
                'fee_category' => '申请费',
                'additional_fee' => 0.00,
                'unit' => '元',
                'description' => '中国外观设计专利申请官费',
                'status' => 1,
                'is_required' => 1,
                'is_valid' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'sort_order' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 7,
                'case_type' => json_encode(['专利']),
                'business_type' => json_encode(['普通新申请']),
                'apply_type' => json_encode(['美国发明专利申请']),
                'country' => json_encode(['美国']),
                'fee_type' => '官费',
                'fee_name' => '美国发明专利申请费',
                'fee_name_en' => 'US Utility Patent Application Fee',
                'currency' => 'USD',
                'fee_code' => 'US_UTILITY_APP_FEE',
                'base_fee' => 1600.00,
                'small_entity_fee' => 800.00,
                'micro_entity_fee' => 400.00,
                'role' => json_encode(['申请人']),
                'use_stage' => json_encode(['新申请']),
                'fee_category' => '申请费',
                'additional_fee' => 0.00,
                'unit' => '美元',
                'description' => '美国发明专利申请官费',
                'status' => 1,
                'is_required' => 1,
                'is_valid' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'sort_order' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        // 检查是否已有数据，避免重复插入
        if (DB::table('fee_configs')->count() == 0) {
            DB::table('fee_configs')->insert($feeConfigs);
        }
    }
}
