<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class FileDescriptionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();
        
        $fileDescriptions = [
            // 中国专利类文件
            [
                'case_type' => '发明专利',
                'country' => '中国',
                'file_category_major' => '申请文件',
                'file_category_minor' => '技术文件',
                'file_name' => '发明专利申请书',
                'file_name_en' => 'Patent Application Form',
                'file_code' => 'CN-INV-APP-001',
                'internal_code' => 'INT-001',
                'sort_order' => 1,
                'file_description' => '发明专利申请的基本申请文件',
                'authorized_client' => '全部客户',
                'authorized_role' => '超级管理员',
                'is_valid' => true,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'case_type' => '发明专利',
                'country' => '中国',
                'file_category_major' => '申请文件',
                'file_category_minor' => '技术文件',
                'file_name' => '发明说明书',
                'file_name_en' => 'Description of Invention',
                'file_code' => 'CN-INV-DESC-001',
                'internal_code' => 'INT-002',
                'sort_order' => 2,
                'file_description' => '详细描述发明技术方案的文件',
                'authorized_client' => '全部客户',
                'authorized_role' => '管理员',
                'is_valid' => true,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'case_type' => '发明专利',
                'country' => '中国',
                'file_category_major' => '申请文件',
                'file_category_minor' => '技术文件',
                'file_name' => '权利要求书',
                'file_name_en' => 'Claims',
                'file_code' => 'CN-INV-CLAIM-001',
                'internal_code' => 'INT-003',
                'sort_order' => 3,
                'file_description' => '确定专利保护范围的法律文件',
                'authorized_client' => '全部客户',
                'authorized_role' => '管理员',
                'is_valid' => true,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'case_type' => '发明专利',
                'country' => '中国',
                'file_category_major' => '申请文件',
                'file_category_minor' => '图样文件',
                'file_name' => '说明书附图',
                'file_name_en' => 'Drawings',
                'file_code' => 'CN-INV-DRW-001',
                'internal_code' => 'INT-004',
                'sort_order' => 4,
                'file_description' => '说明书的附图文件',
                'authorized_client' => '全部客户',
                'authorized_role' => '客户经理',
                'is_valid' => true,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'case_type' => '发明专利',
                'country' => '中国',
                'file_category_major' => '审查文件',
                'file_category_minor' => '法律文件',
                'file_name' => '审查意见通知书',
                'file_name_en' => 'Office Action',
                'file_code' => 'CN-INV-OA-001',
                'internal_code' => 'INT-005',
                'sort_order' => 5,
                'file_description' => '专利局发出的审查意见',
                'authorized_client' => '指定客户',
                'authorized_role' => '管理员',
                'is_valid' => true,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 实用新型专利类文件
            [
                'case_type' => '实用新型',
                'country' => '中国',
                'file_category_major' => '申请文件',
                'file_category_minor' => '技术文件',
                'file_name' => '实用新型专利申请书',
                'file_name_en' => 'Utility Model Application Form',
                'file_code' => 'CN-UM-APP-001',
                'internal_code' => 'INT-006',
                'sort_order' => 6,
                'file_description' => '实用新型专利申请的基本申请文件',
                'authorized_client' => '全部客户',
                'authorized_role' => '超级管理员',
                'is_valid' => true,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'case_type' => '实用新型',
                'country' => '中国',
                'file_category_major' => '授权文件',
                'file_category_minor' => '法律文件',
                'file_name' => '实用新型专利证书',
                'file_name_en' => 'Utility Model Patent Certificate',
                'file_code' => 'CN-UM-CERT-001',
                'internal_code' => 'INT-007',
                'sort_order' => 7,
                'file_description' => '实用新型专利授权证书',
                'authorized_client' => '全部客户',
                'authorized_role' => '普通用户',
                'is_valid' => true,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 商标类文件
            [
                'case_type' => '商标',
                'country' => '中国',
                'file_category_major' => '申请文件',
                'file_category_minor' => '图样文件',
                'file_name' => '商标图样',
                'file_name_en' => 'Trademark Design',
                'file_code' => 'CN-TM-IMG-001',
                'internal_code' => 'INT-008',
                'sort_order' => 8,
                'file_description' => '商标申请的图样文件',
                'authorized_client' => '全部客户',
                'authorized_role' => '客户经理',
                'is_valid' => true,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'case_type' => '商标',
                'country' => '中国',
                'file_category_major' => '申请文件',
                'file_category_minor' => '法律文件',
                'file_name' => '商标注册申请书',
                'file_name_en' => 'Trademark Registration Application',
                'file_code' => 'CN-TM-APP-001',
                'internal_code' => 'INT-009',
                'sort_order' => 9,
                'file_description' => '商标注册申请的基本申请文件',
                'authorized_client' => '全部客户',
                'authorized_role' => '管理员',
                'is_valid' => true,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'case_type' => '商标',
                'country' => '中国',
                'file_category_major' => '审查文件',
                'file_category_minor' => '法律文件',
                'file_name' => '商标实质审查意见书',
                'file_name_en' => 'Trademark Substantive Examination Opinion',
                'file_code' => 'CN-TM-EXAM-001',
                'internal_code' => 'INT-010',
                'sort_order' => 10,
                'file_description' => '商标实质审查阶段的意见书',
                'authorized_client' => '指定客户',
                'authorized_role' => '管理员',
                'is_valid' => true,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 美国专利类文件
            [
                'case_type' => '发明专利',
                'country' => '美国',
                'file_category_major' => '申请文件',
                'file_category_minor' => '技术文件',
                'file_name' => 'US Patent Application',
                'file_name_en' => 'US Patent Application',
                'file_code' => 'US-PAT-APP-001',
                'internal_code' => 'INT-011',
                'sort_order' => 11,
                'file_description' => '美国专利申请文件',
                'authorized_client' => '全部客户',
                'authorized_role' => '超级管理员',
                'is_valid' => true,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'case_type' => '发明专利',
                'country' => '美国',
                'file_category_major' => '缴费文件',
                'file_category_minor' => '财务文件',
                'file_name' => 'USPTO Fee Payment Receipt',
                'file_name_en' => 'USPTO Fee Payment Receipt',
                'file_code' => 'US-PAT-FEE-001',
                'internal_code' => 'INT-012',
                'sort_order' => 12,
                'file_description' => '美国专利局费用缴纳收据',
                'authorized_client' => '指定客户',
                'authorized_role' => '客户经理',
                'is_valid' => true,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 版权类文件
            [
                'case_type' => '版权',
                'country' => '中国',
                'file_category_major' => '申请文件',
                'file_category_minor' => '技术文件',
                'file_name' => '作品登记申请书',
                'file_name_en' => 'Copyright Registration Application',
                'file_code' => 'CN-CR-APP-001',
                'internal_code' => 'INT-013',
                'sort_order' => 13,
                'file_description' => '版权作品登记申请文件',
                'authorized_client' => '全部客户',
                'authorized_role' => '普通用户',
                'is_valid' => true,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'case_type' => '版权',
                'country' => '中国',
                'file_category_major' => '授权文件',
                'file_category_minor' => '法律文件',
                'file_name' => '作品登记证书',
                'file_name_en' => 'Copyright Registration Certificate',
                'file_code' => 'CN-CR-CERT-001',
                'internal_code' => 'INT-014',
                'sort_order' => 14,
                'file_description' => '版权作品登记证书',
                'authorized_client' => '全部客户',
                'authorized_role' => '普通用户',
                'is_valid' => true,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 一个无效的记录用于测试
            [
                'case_type' => '外观设计',
                'country' => '中国',
                'file_category_major' => '申请文件',
                'file_category_minor' => '图样文件',
                'file_name' => '外观设计图片（已废弃）',
                'file_name_en' => 'Design Images (Deprecated)',
                'file_code' => 'CN-DES-IMG-OLD',
                'internal_code' => 'INT-015',
                'sort_order' => 15,
                'file_description' => '已废弃的外观设计图片格式',
                'authorized_client' => '指定客户',
                'authorized_role' => '管理员',
                'is_valid' => false,
                'updated_by' => '系统管理员',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('file_descriptions')->insert($fileDescriptions);

        if ($this->command) {
            $this->command->info('文件描述设置数据插入成功！共插入 ' . count($fileDescriptions) . ' 条记录。');
        }
    }
}
