<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ManuscriptScoringItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 审核打分项表种子数据
     */
    public function run()
    {
        $manuscriptScoringItems = [
            [
                'sort' => 1,
                'name' => '技术方案完整性',
                'code' => 'TECH_SOLUTION_COMPLETENESS',
                'major_category' => '技术质量',
                'minor_category' => '方案完整性',
                'description' => '技术方案是否完整，包括技术背景、技术问题、解决方案等',
                'score' => 20,
                'max_score' => 20,
                'weight' => 1.00,
                'status' => 1,
                'sort_order' => 1,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 2,
                'name' => '技术创新性',
                'code' => 'TECH_INNOVATION',
                'major_category' => '技术质量',
                'minor_category' => '创新程度',
                'description' => '技术方案的创新程度，是否具有突破性',
                'score' => 25,
                'max_score' => 25,
                'weight' => 1.20,
                'status' => 1,
                'sort_order' => 2,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 3,
                'name' => '技术实用性',
                'code' => 'TECH_PRACTICALITY',
                'major_category' => '技术质量',
                'minor_category' => '实用程度',
                'description' => '技术方案的实用性和可操作性',
                'score' => 15,
                'max_score' => 15,
                'weight' => 1.00,
                'status' => 1,
                'sort_order' => 3,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 4,
                'name' => '权利要求书质量',
                'code' => 'CLAIMS_QUALITY',
                'major_category' => '文件质量',
                'minor_category' => '权利要求',
                'description' => '权利要求书的撰写质量，保护范围是否合理',
                'score' => 20,
                'max_score' => 20,
                'weight' => 1.10,
                'status' => 1,
                'sort_order' => 4,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 5,
                'name' => '说明书质量',
                'code' => 'SPECIFICATION_QUALITY',
                'major_category' => '文件质量',
                'minor_category' => '说明书',
                'description' => '说明书的撰写质量，技术方案描述是否清楚',
                'score' => 15,
                'max_score' => 15,
                'weight' => 1.00,
                'status' => 1,
                'sort_order' => 5,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 6,
                'name' => '附图质量',
                'code' => 'DRAWINGS_QUALITY',
                'major_category' => '文件质量',
                'minor_category' => '附图',
                'description' => '附图的质量和完整性，是否能够清楚表达技术方案',
                'score' => 10,
                'max_score' => 10,
                'weight' => 0.80,
                'status' => 1,
                'sort_order' => 6,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 7,
                'name' => '现有技术检索',
                'code' => 'PRIOR_ART_SEARCH',
                'major_category' => '检索质量',
                'minor_category' => '现有技术',
                'description' => '现有技术检索的全面性和准确性',
                'score' => 15,
                'max_score' => 15,
                'weight' => 1.00,
                'status' => 1,
                'sort_order' => 7,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 8,
                'name' => '新颖性分析',
                'code' => 'NOVELTY_ANALYSIS',
                'major_category' => '检索质量',
                'minor_category' => '新颖性',
                'description' => '新颖性分析的准确性和深度',
                'score' => 20,
                'max_score' => 20,
                'weight' => 1.15,
                'status' => 1,
                'sort_order' => 8,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 9,
                'name' => '创造性分析',
                'code' => 'INVENTIVENESS_ANALYSIS',
                'major_category' => '检索质量',
                'minor_category' => '创造性',
                'description' => '创造性分析的准确性和深度',
                'score' => 25,
                'max_score' => 25,
                'weight' => 1.25,
                'status' => 1,
                'sort_order' => 9,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 10,
                'name' => '文件格式规范',
                'code' => 'FORMAT_COMPLIANCE',
                'major_category' => '格式规范',
                'minor_category' => '文件格式',
                'description' => '申请文件格式是否符合官方要求',
                'score' => 5,
                'max_score' => 5,
                'weight' => 0.50,
                'status' => 1,
                'sort_order' => 10,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 11,
                'name' => '语言表达质量',
                'code' => 'LANGUAGE_QUALITY',
                'major_category' => '格式规范',
                'minor_category' => '语言表达',
                'description' => '文件语言表达的准确性和专业性',
                'score' => 10,
                'max_score' => 10,
                'weight' => 0.80,
                'status' => 1,
                'sort_order' => 11,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 12,
                'name' => '客户沟通配合',
                'code' => 'CLIENT_COOPERATION',
                'major_category' => '服务质量',
                'minor_category' => '客户配合',
                'description' => '客户在申请过程中的配合程度',
                'score' => 10,
                'max_score' => 10,
                'weight' => 0.60,
                'status' => 1,
                'sort_order' => 12,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 13,
                'name' => '时间进度控制',
                'code' => 'TIME_MANAGEMENT',
                'major_category' => '服务质量',
                'minor_category' => '进度控制',
                'description' => '申请进度的控制和时间节点的把握',
                'score' => 10,
                'max_score' => 10,
                'weight' => 0.80,
                'status' => 1,
                'sort_order' => 13,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 14,
                'name' => '后续维护建议',
                'code' => 'MAINTENANCE_ADVICE',
                'major_category' => '服务质量',
                'minor_category' => '后续服务',
                'description' => '对后续专利维护和运营的建议质量',
                'score' => 5,
                'max_score' => 5,
                'weight' => 0.60,
                'status' => 1,
                'sort_order' => 14,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 15,
                'name' => '整体评价',
                'code' => 'OVERALL_EVALUATION',
                'major_category' => '综合评价',
                'minor_category' => '整体质量',
                'description' => '对整个申请文件和服务的综合评价',
                'score' => 15,
                'max_score' => 15,
                'weight' => 1.00,
                'status' => 1,
                'sort_order' => 15,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        // 检查是否已有数据，避免重复插入
        if (DB::table('manuscript_scoring_items')->count() == 0) {
            DB::table('manuscript_scoring_items')->insert($manuscriptScoringItems);
        }
    }
}
