<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ProcessInformation;
use Illuminate\Support\Facades\DB;

class ProcessInformationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // 清空表数据
        DB::table('process_informations')->truncate();

        $processInformations = [
            // 专利相关处理事项
            [
                'case_type' => '专利',
                'business_type' => ['发明专利', '实用新型专利', '外观设计专利'],
                'application_type' => ['新申请', 'PCT申请'],
                'country' => ['中国', '美国', '欧洲', '日本'],
                'process_name' => '专利申请文件撰写',
                'flow_completed' => 0,
                'proposal_inquiry' => 1,
                'data_updater_inquiry' => 1,
                'update_case_handler' => 1,
                'process_status' => ['草稿', '待提交', '已提交'],
                'case_phase' => '申请阶段',
                'process_type' => '撰写类',
                'is_case_node' => 1,
                'is_commission' => 1,
                'is_valid' => 1,
                'sort_order' => 1,
                'consultant_contract' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'case_type' => '专利',
                'business_type' => ['发明专利', '实用新型专利'],
                'application_type' => ['新申请'],
                'country' => ['中国'],
                'process_name' => '实质审查请求',
                'flow_completed' => 0,
                'proposal_inquiry' => 1,
                'data_updater_inquiry' => 1,
                'update_case_handler' => 1,
                'process_status' => ['待处理', '已处理'],
                'case_phase' => '审查阶段',
                'process_type' => '官方程序',
                'is_case_node' => 1,
                'is_commission' => 0,
                'is_valid' => 1,
                'sort_order' => 2,
                'consultant_contract' => 0,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'case_type' => '专利',
                'business_type' => ['发明专利', '实用新型专利', '外观设计专利'],
                'application_type' => ['新申请'],
                'country' => ['中国'],
                'process_name' => '答复审查意见通知书',
                'flow_completed' => 0,
                'proposal_inquiry' => 1,
                'data_updater_inquiry' => 1,
                'update_case_handler' => 1,
                'process_status' => ['待答复', '已答复'],
                'case_phase' => '审查阶段',
                'process_type' => '答复类',
                'is_case_node' => 1,
                'is_commission' => 1,
                'is_valid' => 1,
                'sort_order' => 3,
                'consultant_contract' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'case_type' => '专利',
                'business_type' => ['发明专利', '实用新型专利', '外观设计专利'],
                'application_type' => ['新申请'],
                'country' => ['中国'],
                'process_name' => '缴纳年费',
                'flow_completed' => 0,
                'proposal_inquiry' => 0,
                'data_updater_inquiry' => 1,
                'update_case_handler' => 0,
                'process_status' => ['待缴费', '已缴费'],
                'case_phase' => '维护阶段',
                'process_type' => '缴费类',
                'is_case_node' => 0,
                'is_commission' => 0,
                'is_valid' => 1,
                'sort_order' => 4,
                'consultant_contract' => 0,
                'created_by' => 1,
                'updated_by' => 1,
            ],

            // 商标相关处理事项
            [
                'case_type' => '商标',
                'business_type' => ['商标注册', '商标续展', '商标转让'],
                'application_type' => ['新申请', '马德里申请'],
                'country' => ['中国', '美国', '欧盟', '日本'],
                'process_name' => '商标申请文件准备',
                'flow_completed' => 0,
                'proposal_inquiry' => 1,
                'data_updater_inquiry' => 1,
                'update_case_handler' => 1,
                'process_status' => ['草稿', '待提交', '已提交'],
                'case_phase' => '申请阶段',
                'process_type' => '申请类',
                'is_case_node' => 1,
                'is_commission' => 1,
                'is_valid' => 1,
                'sort_order' => 5,
                'consultant_contract' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'case_type' => '商标',
                'business_type' => ['商标注册'],
                'application_type' => ['新申请'],
                'country' => ['中国'],
                'process_name' => '商标驳回复审',
                'flow_completed' => 0,
                'proposal_inquiry' => 1,
                'data_updater_inquiry' => 1,
                'update_case_handler' => 1,
                'process_status' => ['待处理', '已处理'],
                'case_phase' => '复审阶段',
                'process_type' => '复审类',
                'is_case_node' => 1,
                'is_commission' => 1,
                'is_valid' => 1,
                'sort_order' => 6,
                'consultant_contract' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'case_type' => '商标',
                'business_type' => ['商标续展'],
                'application_type' => ['续展申请'],
                'country' => ['中国'],
                'process_name' => '商标续展申请',
                'flow_completed' => 0,
                'proposal_inquiry' => 1,
                'data_updater_inquiry' => 1,
                'update_case_handler' => 1,
                'process_status' => ['待处理', '已处理'],
                'case_phase' => '维护阶段',
                'process_type' => '续展类',
                'is_case_node' => 1,
                'is_commission' => 1,
                'is_valid' => 1,
                'sort_order' => 7,
                'consultant_contract' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],

            // 版权相关处理事项
            [
                'case_type' => '版权',
                'business_type' => ['软件著作权', '作品著作权'],
                'application_type' => ['新申请'],
                'country' => ['中国'],
                'process_name' => '版权登记申请',
                'flow_completed' => 0,
                'proposal_inquiry' => 1,
                'data_updater_inquiry' => 1,
                'update_case_handler' => 1,
                'process_status' => ['草稿', '待提交', '已提交'],
                'case_phase' => '申请阶段',
                'process_type' => '申请类',
                'is_case_node' => 1,
                'is_commission' => 1,
                'is_valid' => 1,
                'sort_order' => 8,
                'consultant_contract' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'case_type' => '版权',
                'business_type' => ['软件著作权', '作品著作权'],
                'application_type' => ['新申请'],
                'country' => ['中国'],
                'process_name' => '版权补正',
                'flow_completed' => 0,
                'proposal_inquiry' => 1,
                'data_updater_inquiry' => 1,
                'update_case_handler' => 1,
                'process_status' => ['待补正', '已补正'],
                'case_phase' => '审查阶段',
                'process_type' => '补正类',
                'is_case_node' => 1,
                'is_commission' => 1,
                'is_valid' => 1,
                'sort_order' => 9,
                'consultant_contract' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],

            // 科技服务相关处理事项
            [
                'case_type' => '科技服务',
                'business_type' => ['高新技术企业认定', '专精特新认定'],
                'application_type' => ['新申请', '复审申请'],
                'country' => ['中国'],
                'process_name' => '高新技术企业认定申请',
                'flow_completed' => 0,
                'proposal_inquiry' => 1,
                'data_updater_inquiry' => 1,
                'update_case_handler' => 1,
                'process_status' => ['材料准备', '已提交', '审核中'],
                'case_phase' => '申请阶段',
                'process_type' => '认定类',
                'is_case_node' => 1,
                'is_commission' => 1,
                'is_valid' => 1,
                'sort_order' => 10,
                'consultant_contract' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'case_type' => '科技服务',
                'business_type' => ['政府项目申报'],
                'application_type' => ['新申请'],
                'country' => ['中国'],
                'process_name' => '政府项目申报',
                'flow_completed' => 0,
                'proposal_inquiry' => 1,
                'data_updater_inquiry' => 1,
                'update_case_handler' => 1,
                'process_status' => ['材料准备', '已申报', '评审中'],
                'case_phase' => '申报阶段',
                'process_type' => '申报类',
                'is_case_node' => 1,
                'is_commission' => 1,
                'is_valid' => 1,
                'sort_order' => 11,
                'consultant_contract' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],

            // 通用处理事项
            [
                'case_type' => '通用',
                'business_type' => ['专利', '商标', '版权', '科技服务'],
                'application_type' => ['所有类型'],
                'country' => ['所有国家'],
                'process_name' => '客户沟通',
                'flow_completed' => 0,
                'proposal_inquiry' => 0,
                'data_updater_inquiry' => 0,
                'update_case_handler' => 0,
                'process_status' => ['进行中', '已完成'],
                'case_phase' => '全程',
                'process_type' => '沟通类',
                'is_case_node' => 0,
                'is_commission' => 0,
                'is_valid' => 1,
                'sort_order' => 12,
                'consultant_contract' => 0,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'case_type' => '通用',
                'business_type' => ['专利', '商标', '版权', '科技服务'],
                'application_type' => ['所有类型'],
                'country' => ['所有国家'],
                'process_name' => '文件整理归档',
                'flow_completed' => 0,
                'proposal_inquiry' => 0,
                'data_updater_inquiry' => 0,
                'update_case_handler' => 0,
                'process_status' => ['待整理', '已归档'],
                'case_phase' => '完结阶段',
                'process_type' => '归档类',
                'is_case_node' => 0,
                'is_commission' => 0,
                'is_valid' => 1,
                'sort_order' => 13,
                'consultant_contract' => 0,
                'created_by' => 1,
                'updated_by' => 1,
            ]
        ];

        foreach ($processInformations as $info) {
            // 检查是否已存在相同的处理事项
            $exists = ProcessInformation::where('process_name', $info['process_name'])
                ->where('case_type', $info['case_type'])
                ->exists();

            if (!$exists) {
                ProcessInformation::create($info);
            }
        }

        $this->command->info('ProcessInformation seeder completed successfully!');
    }
}
