<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // 清空表数据
        DB::table('products')->truncate();

        $products = [
            // 专利产品
            [
                'sort' => 1,
                'product_code' => 'PT001',
                'project_type' => '专利',
                'apply_type' => '发明专利',
                'specification' => '标准版',
                'product_name' => '发明专利申请（标准版）',
                'official_fee' => 900.00,
                'standard_price' => 8000.00,
                'min_price' => 6000.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 2,
                'product_code' => 'PT002',
                'project_type' => '专利',
                'apply_type' => '发明专利',
                'specification' => '加急版',
                'product_name' => '发明专利申请（加急版）',
                'official_fee' => 900.00,
                'standard_price' => 12000.00,
                'min_price' => 9000.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 3,
                'product_code' => 'PT003',
                'project_type' => '专利',
                'apply_type' => '实用新型专利',
                'specification' => '标准版',
                'product_name' => '实用新型专利申请（标准版）',
                'official_fee' => 500.00,
                'standard_price' => 3000.00,
                'min_price' => 2200.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 4,
                'product_code' => 'PT004',
                'project_type' => '专利',
                'apply_type' => '实用新型专利',
                'specification' => '加急版',
                'product_name' => '实用新型专利申请（加急版）',
                'official_fee' => 500.00,
                'standard_price' => 4500.00,
                'min_price' => 3300.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 5,
                'product_code' => 'PT005',
                'project_type' => '专利',
                'apply_type' => '外观设计专利',
                'specification' => '标准版',
                'product_name' => '外观设计专利申请（标准版）',
                'official_fee' => 500.00,
                'standard_price' => 1800.00,
                'min_price' => 1300.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 6,
                'product_code' => 'PT006',
                'project_type' => '专利',
                'apply_type' => '发明专利',
                'specification' => '答复审查意见',
                'product_name' => '发明专利答复审查意见',
                'official_fee' => 0.00,
                'standard_price' => 3000.00,
                'min_price' => 2000.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 7,
                'product_code' => 'PT007',
                'project_type' => '专利',
                'apply_type' => '实用新型专利',
                'specification' => '答复审查意见',
                'product_name' => '实用新型专利答复审查意见',
                'official_fee' => 0.00,
                'standard_price' => 2000.00,
                'min_price' => 1500.00,
                'is_valid' => true,
                'update_user' => 1,
            ],

            // 商标产品
            [
                'sort' => 8,
                'product_code' => 'TM001',
                'project_type' => '商标',
                'apply_type' => '商标注册',
                'specification' => '标准版',
                'product_name' => '商标注册申请（标准版）',
                'official_fee' => 270.00,
                'standard_price' => 1200.00,
                'min_price' => 800.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 9,
                'product_code' => 'TM002',
                'project_type' => '商标',
                'apply_type' => '商标注册',
                'specification' => '加急版',
                'product_name' => '商标注册申请（加急版）',
                'official_fee' => 270.00,
                'standard_price' => 1800.00,
                'min_price' => 1200.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 10,
                'product_code' => 'TM003',
                'project_type' => '商标',
                'apply_type' => '商标续展',
                'specification' => '标准版',
                'product_name' => '商标续展申请（标准版）',
                'official_fee' => 500.00,
                'standard_price' => 1500.00,
                'min_price' => 1000.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 11,
                'product_code' => 'TM004',
                'project_type' => '商标',
                'apply_type' => '商标转让',
                'specification' => '标准版',
                'product_name' => '商标转让申请（标准版）',
                'official_fee' => 500.00,
                'standard_price' => 1200.00,
                'min_price' => 800.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 12,
                'product_code' => 'TM005',
                'project_type' => '商标',
                'apply_type' => '商标驳回复审',
                'specification' => '标准版',
                'product_name' => '商标驳回复审申请',
                'official_fee' => 750.00,
                'standard_price' => 3000.00,
                'min_price' => 2000.00,
                'is_valid' => true,
                'update_user' => 1,
            ],

            // 版权产品
            [
                'sort' => 13,
                'product_code' => 'CR001',
                'project_type' => '版权',
                'apply_type' => '软件著作权',
                'specification' => '标准版',
                'product_name' => '软件著作权登记（标准版）',
                'official_fee' => 300.00,
                'standard_price' => 1500.00,
                'min_price' => 1000.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 14,
                'product_code' => 'CR002',
                'project_type' => '版权',
                'apply_type' => '软件著作权',
                'specification' => '加急版',
                'product_name' => '软件著作权登记（加急版）',
                'official_fee' => 300.00,
                'standard_price' => 2500.00,
                'min_price' => 1800.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 15,
                'product_code' => 'CR003',
                'project_type' => '版权',
                'apply_type' => '作品著作权',
                'specification' => '标准版',
                'product_name' => '作品著作权登记（标准版）',
                'official_fee' => 300.00,
                'standard_price' => 1200.00,
                'min_price' => 800.00,
                'is_valid' => true,
                'update_user' => 1,
            ],

            // 科技服务产品
            [
                'sort' => 16,
                'product_code' => 'TS001',
                'project_type' => '科技服务',
                'apply_type' => '高新技术企业认定',
                'specification' => '标准版',
                'product_name' => '高新技术企业认定申请',
                'official_fee' => 0.00,
                'standard_price' => 15000.00,
                'min_price' => 12000.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 17,
                'product_code' => 'TS002',
                'project_type' => '科技服务',
                'apply_type' => '专精特新认定',
                'specification' => '标准版',
                'product_name' => '专精特新企业认定申请',
                'official_fee' => 0.00,
                'standard_price' => 8000.00,
                'min_price' => 6000.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 18,
                'product_code' => 'TS003',
                'project_type' => '科技服务',
                'apply_type' => '政府项目申报',
                'specification' => '标准版',
                'product_name' => '政府科技项目申报',
                'official_fee' => 0.00,
                'standard_price' => 20000.00,
                'min_price' => 15000.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 19,
                'product_code' => 'TS004',
                'project_type' => '科技服务',
                'apply_type' => '知识产权贯标',
                'specification' => '标准版',
                'product_name' => '知识产权管理体系认证',
                'official_fee' => 0.00,
                'standard_price' => 25000.00,
                'min_price' => 20000.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 20,
                'product_code' => 'TS005',
                'project_type' => '科技服务',
                'apply_type' => '研发费用加计扣除',
                'specification' => '标准版',
                'product_name' => '研发费用加计扣除申报',
                'official_fee' => 0.00,
                'standard_price' => 5000.00,
                'min_price' => 3500.00,
                'is_valid' => true,
                'update_user' => 1,
            ],

            // 国际业务产品
            [
                'sort' => 21,
                'product_code' => 'IN001',
                'project_type' => '国际专利',
                'apply_type' => 'PCT申请',
                'specification' => '标准版',
                'product_name' => 'PCT国际专利申请',
                'official_fee' => 1330.00,
                'standard_price' => 12000.00,
                'min_price' => 9000.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 22,
                'product_code' => 'IN002',
                'project_type' => '国际商标',
                'apply_type' => '马德里申请',
                'specification' => '标准版',
                'product_name' => '马德里国际商标申请',
                'official_fee' => 653.00,
                'standard_price' => 5000.00,
                'min_price' => 3500.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 23,
                'product_code' => 'IN003',
                'project_type' => '国际专利',
                'apply_type' => '美国专利申请',
                'specification' => '标准版',
                'product_name' => '美国发明专利申请',
                'official_fee' => 1600.00,
                'standard_price' => 18000.00,
                'min_price' => 15000.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 24,
                'product_code' => 'IN004',
                'project_type' => '国际专利',
                'apply_type' => '欧洲专利申请',
                'specification' => '标准版',
                'product_name' => '欧洲发明专利申请',
                'official_fee' => 1470.00,
                'standard_price' => 20000.00,
                'min_price' => 16000.00,
                'is_valid' => true,
                'update_user' => 1,
            ],

            // 咨询服务产品
            [
                'sort' => 25,
                'product_code' => 'CS001',
                'project_type' => '咨询服务',
                'apply_type' => '专利检索',
                'specification' => '标准版',
                'product_name' => '专利技术检索分析',
                'official_fee' => 0.00,
                'standard_price' => 2000.00,
                'min_price' => 1500.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 26,
                'product_code' => 'CS002',
                'project_type' => '咨询服务',
                'apply_type' => '商标检索',
                'specification' => '标准版',
                'product_name' => '商标注册风险评估',
                'official_fee' => 0.00,
                'standard_price' => 800.00,
                'min_price' => 500.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 27,
                'product_code' => 'CS003',
                'project_type' => '咨询服务',
                'apply_type' => '知识产权培训',
                'specification' => '标准版',
                'product_name' => '企业知识产权培训',
                'official_fee' => 0.00,
                'standard_price' => 5000.00,
                'min_price' => 3000.00,
                'is_valid' => true,
                'update_user' => 1,
            ],
            [
                'sort' => 28,
                'product_code' => 'CS004',
                'project_type' => '咨询服务',
                'apply_type' => '知识产权布局',
                'specification' => '标准版',
                'product_name' => '知识产权战略布局',
                'official_fee' => 0.00,
                'standard_price' => 15000.00,
                'min_price' => 10000.00,
                'is_valid' => true,
                'update_user' => 1,
            ]
        ];

        foreach ($products as $product) {
            // 检查是否已存在相同的产品
            $exists = Product::where('product_code', $product['product_code'])->exists();

            if (!$exists) {
                Product::create($product);
            }
        }

        $this->command->info('Products seeder completed successfully!');
    }
}
