<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TechServiceTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 科技服务类型表种子数据
     */
    public function run()
    {
        $techServiceTypes = [
            [
                'sort' => 1,
                'name' => '高新技术企业认定',
                'code' => 'HIGH_TECH_ENTERPRISE',
                'apply_type' => '企业认定',
                'service_level' => '国家级',
                'main_area' => '全国',
                'project_year' => '2024',
                'deadline' => '2024-12-31',
                'batch_number' => 1,
                'category' => '企业认定',
                'description' => '国家高新技术企业认定，享受税收优惠政策',
                'status' => 1,
                'sort_order' => 1,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 2,
                'name' => '科技型中小企业评价',
                'code' => 'TECH_SME_EVALUATION',
                'apply_type' => '科技服务',
                'service_level' => '国家级',
                'main_area' => '全国',
                'project_year' => '2024',
                'deadline' => '2024-11-30',
                'batch_number' => 2,
                'category' => '企业评价',
                'description' => '科技型中小企业评价，获得研发费用加计扣除资格',
                'status' => 1,
                'sort_order' => 2,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 3,
                'name' => '专精特新小巨人企业',
                'code' => 'SPECIALIZED_LITTLE_GIANT',
                'apply_type' => '企业认定',
                'service_level' => '国家级',
                'main_area' => '全国',
                'project_year' => '2024',
                'deadline' => '2024-10-31',
                'batch_number' => 1,
                'category' => '企业认定',
                'description' => '专精特新小巨人企业认定，享受多项政策支持',
                'status' => 1,
                'sort_order' => 3,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 4,
                'name' => '科技成果转化项目',
                'code' => 'TECH_ACHIEVEMENT_TRANSFORM',
                'apply_type' => '科技服务',
                'service_level' => '国家级',
                'main_area' => '全国',
                'project_year' => '2024',
                'deadline' => '2024-06-30',
                'batch_number' => 1,
                'category' => '成果转化',
                'description' => '科技成果转化项目申报',
                'status' => 1,
                'sort_order' => 4,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 5,
                'name' => '技术转移服务',
                'code' => 'TECH_TRANSFER_SERVICE',
                'apply_type' => '科技服务',
                'service_level' => '省级',
                'main_area' => '各省市',
                'project_year' => '2024',
                'deadline' => '2024-08-31',
                'batch_number' => 1,
                'category' => '技术转移',
                'description' => '技术转移服务平台建设',
                'status' => 1,
                'sort_order' => 5,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 6,
                'name' => '科技咨询服务',
                'code' => 'TECH_CONSULTING_SERVICE',
                'apply_type' => '科技服务',
                'service_level' => '国家级',
                'main_area' => '全国',
                'project_year' => '2024',
                'deadline' => '2024-09-30',
                'batch_number' => 2,
                'category' => '咨询服务',
                'description' => '科技咨询服务项目',
                'status' => 1,
                'sort_order' => 6,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 7,
                'name' => '科技评估服务',
                'code' => 'TECH_EVALUATION_SERVICE',
                'apply_type' => '科技服务',
                'service_level' => '国家级',
                'main_area' => '全国',
                'project_year' => '2024',
                'deadline' => '2024-03-31',
                'batch_number' => 1,
                'category' => '评估服务',
                'description' => '科技项目评估服务',
                'status' => 1,
                'sort_order' => 7,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 8,
                'name' => '科技金融服务',
                'code' => 'TECH_FINANCE_SERVICE',
                'apply_type' => '科技服务',
                'service_level' => '省级',
                'main_area' => '各省市',
                'project_year' => '2024',
                'deadline' => '2024-07-31',
                'batch_number' => 2,
                'category' => '科研项目',
                'description' => '省级科技计划项目申报',
                'status' => 1,
                'sort_order' => 8,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 9,
                'name' => '市级科技创新项目',
                'code' => 'CITY_INNOVATION_PROJECT',
                'apply_type' => '项目申报',
                'service_level' => '市级',
                'main_area' => '各地市',
                'project_year' => '2024',
                'deadline' => '2024-05-31',
                'batch_number' => 3,
                'category' => '科研项目',
                'description' => '市级科技创新项目申报',
                'status' => 1,
                'sort_order' => 9,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sort' => 10,
                'name' => '知识产权贯标认证',
                'code' => 'IP_MANAGEMENT_CERTIFICATION',
                'apply_type' => '认证申报',
                'service_level' => '国家级',
                'main_area' => '全国',
                'project_year' => '2024',
                'deadline' => '2024-12-31',
                'batch_number' => 4,
                'category' => '知识产权',
                'description' => '企业知识产权管理规范认证',
                'status' => 1,
                'sort_order' => 10,
                'updater' => '系统管理员',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        // 检查是否已有数据，避免重复插入
        if (DB::table('tech_service_types')->count() == 0) {
            DB::table('tech_service_types')->insert($techServiceTypes);
        }
    }
}
