<?php

require_once 'vendor/autoload.php';

use App\Models\Customer;
use App\Models\User;
use Carbon\Carbon;

// 启动Laravel应用
$app = require_once 'bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

// 清空现有数据
Customer::truncate();

// 确保有用户数据
$users = User::all();
if ($users->isEmpty()) {
    // 创建一些测试用户
    $users = collect([
        User::create([
            'username' => 'zhangsan',
            'real_name' => '张三',
            'email' => 'zhangsan@example.com',
            'password' => bcrypt('password'),
            'status' => 1,
        ]),
        User::create([
            'username' => 'lisi',
            'real_name' => '李四',
            'email' => 'lisi@example.com',
            'password' => bcrypt('password'),
            'status' => 1,
        ]),
        User::create([
            'username' => 'wangwu',
            'real_name' => '王五',
            'email' => 'wangwu@example.com',
            'password' => bcrypt('password'),
            'status' => 1,
        ]),
    ]);
}

// 创建测试客户数据
$customers = [
    [
        'customer_code' => 'C20250810001',
        'customer_name' => '北京科技创新有限公司',
        'name' => '北京科技创新有限公司',
        'credit_code' => '91110000123456789A',
        'customer_type' => 1,
        'customer_level' => 1,
        'level' => 'A',
        'industry' => '软件和信息技术服务业',
        'contact_phone' => '010-12345678',
        'contact_email' => 'contact@bjkjcx.com',
        'business_person_id' => $users->first()->id,
        'business_person' => $users->first()->real_name,
        'business_assistant_id' => $users->skip(1)->first()->id,
        'business_assistant' => $users->skip(1)->first()->real_name,
        'business_partner_id' => $users->skip(2)->first()->id,
        'business_partner' => $users->skip(2)->first()->real_name,
        'company_manager' => '张总',
        'customer_status' => 1,
        'latest_contract_date' => '2024-12-01',
        'contract_count' => 5,
        'total_amount' => 500000.00,
        'province' => '北京',
        'city' => '北京',
        'district' => '海淀区',
        'case_count' => 8,
        'customer_no' => 'KH001',
        'economic_category' => 'I',
        'economic_door' => 'I 信息传输、软件和信息技术服务业',
        'economic_big_class' => 'I65 软件和信息技术服务业',
        'economic_mid_class' => 'I651 软件开发',
        'economic_small_class' => 'I6510 基础软件开发',
        'sales_2021' => 2000000.00,
        'research_fee_2021' => 200000.00,
        'loan_2021' => 500000.00,
        'high_tech_enterprise' => true,
        'province_enterprise' => true,
        'city_enterprise' => false,
        'province_tech_center' => true,
        'ip_standard' => true,
        'it_standard' => true,
        'innovation_index' => 1,
        'price_index' => 2,
        'remarks' => '重要客户，技术实力强',
        'remark' => '重要客户，技术实力强',
        'industrial_park' => '中关村软件园',
        'created_by' => $users->first()->id,
        'updated_by' => $users->first()->id,
        'created_at' => Carbon::now()->subDays(30),
        'updated_at' => Carbon::now()->subDays(5),
    ],
    [
        'customer_code' => 'C20250810002',
        'customer_name' => '上海智能制造股份有限公司',
        'name' => '上海智能制造股份有限公司',
        'credit_code' => '91310000987654321B',
        'customer_type' => 1,
        'customer_level' => 2,
        'level' => 'B',
        'industry' => '通用设备制造业',
        'contact_phone' => '021-87654321',
        'contact_email' => 'info@shznzz.com',
        'business_person_id' => $users->skip(1)->first()->id,
        'business_person' => $users->skip(1)->first()->real_name,
        'business_assistant_id' => $users->first()->id,
        'business_assistant' => $users->first()->real_name,
        'company_manager' => '李总',
        'customer_status' => 1,
        'latest_contract_date' => '2024-11-15',
        'contract_count' => 3,
        'total_amount' => 300000.00,
        'province' => '上海',
        'city' => '上海',
        'district' => '浦东新区',
        'case_count' => 5,
        'customer_no' => 'KH002',
        'economic_category' => 'C',
        'economic_door' => 'C 制造业',
        'economic_big_class' => 'C34 通用设备制造业',
        'economic_mid_class' => 'C341 锅炉及原动设备制造',
        'economic_small_class' => 'C3411 锅炉制造',
        'sales_2021' => 5000000.00,
        'research_fee_2021' => 300000.00,
        'loan_2021' => 1000000.00,
        'high_tech_enterprise' => false,
        'province_enterprise' => true,
        'city_enterprise' => true,
        'province_tech_center' => false,
        'ip_standard' => false,
        'it_standard' => true,
        'innovation_index' => 2,
        'price_index' => 1,
        'remarks' => '制造业客户，有发展潜力',
        'remark' => '制造业客户，有发展潜力',
        'industrial_park' => '张江高科技园区',
        'created_by' => $users->skip(1)->first()->id,
        'updated_by' => $users->skip(1)->first()->id,
        'created_at' => Carbon::now()->subDays(25),
        'updated_at' => Carbon::now()->subDays(3),
    ],
    [
        'customer_code' => 'C20250810003',
        'customer_name' => '深圳新能源科技有限公司',
        'name' => '深圳新能源科技有限公司',
        'credit_code' => '91440300555666777C',
        'customer_type' => 1,
        'customer_level' => 1,
        'level' => 'A',
        'industry' => '电气机械和器材制造业',
        'contact_phone' => '0755-88888888',
        'contact_email' => 'service@szxny.com',
        'business_person_id' => $users->skip(2)->first()->id,
        'business_person' => $users->skip(2)->first()->real_name,
        'business_assistant_id' => $users->first()->id,
        'business_assistant' => $users->first()->real_name,
        'business_partner_id' => $users->skip(1)->first()->id,
        'business_partner' => $users->skip(1)->first()->real_name,
        'company_manager' => '王总',
        'customer_status' => 1,
        'latest_contract_date' => '2024-12-20',
        'contract_count' => 7,
        'total_amount' => 800000.00,
        'province' => '广东',
        'city' => '深圳',
        'district' => '南山区',
        'case_count' => 12,
        'customer_no' => 'KH003',
        'economic_category' => 'C',
        'economic_door' => 'C 制造业',
        'economic_big_class' => 'C38 电气机械和器材制造业',
        'economic_mid_class' => 'C384 电池制造',
        'economic_small_class' => 'C3841 锂离子电池制造',
        'sales_2021' => 8000000.00,
        'research_fee_2021' => 800000.00,
        'loan_2021' => 2000000.00,
        'high_tech_enterprise' => true,
        'province_enterprise' => true,
        'city_enterprise' => true,
        'province_tech_center' => true,
        'ip_standard' => true,
        'it_standard' => false,
        'innovation_index' => 1,
        'price_index' => 1,
        'remarks' => '新能源行业领军企业',
        'remark' => '新能源行业领军企业',
        'industrial_park' => '深圳高新技术产业园',
        'created_by' => $users->skip(2)->first()->id,
        'updated_by' => $users->skip(2)->first()->id,
        'created_at' => Carbon::now()->subDays(20),
        'updated_at' => Carbon::now()->subDays(1),
    ],
    [
        'customer_code' => 'C20250810004',
        'customer_name' => '杭州生物医药有限公司',
        'name' => '杭州生物医药有限公司',
        'credit_code' => '91330100111222333D',
        'customer_type' => 1,
        'customer_level' => 3,
        'level' => 'C',
        'industry' => '医药制造业',
        'contact_phone' => '0571-99999999',
        'contact_email' => 'contact@hzswyy.com',
        'business_person_id' => $users->first()->id,
        'business_person' => $users->first()->real_name,
        'company_manager' => '赵总',
        'customer_status' => 1,
        'latest_contract_date' => '2024-10-30',
        'contract_count' => 2,
        'total_amount' => 150000.00,
        'province' => '浙江',
        'city' => '杭州',
        'district' => '西湖区',
        'case_count' => 3,
        'customer_no' => 'KH004',
        'economic_category' => 'C',
        'economic_door' => 'C 制造业',
        'economic_big_class' => 'C27 医药制造业',
        'economic_mid_class' => 'C271 化学药品原料药制造',
        'economic_small_class' => 'C2710 化学药品原料药制造',
        'sales_2021' => 1200000.00,
        'research_fee_2021' => 150000.00,
        'loan_2021' => 300000.00,
        'high_tech_enterprise' => false,
        'province_enterprise' => false,
        'city_enterprise' => true,
        'province_tech_center' => false,
        'ip_standard' => false,
        'it_standard' => false,
        'innovation_index' => 3,
        'price_index' => 3,
        'remarks' => '潜在客户，需要重点跟进',
        'remark' => '潜在客户，需要重点跟进',
        'industrial_park' => '杭州医药港',
        'created_by' => $users->first()->id,
        'updated_by' => $users->first()->id,
        'created_at' => Carbon::now()->subDays(15),
        'updated_at' => Carbon::now()->subDays(2),
    ],
];

foreach ($customers as $customerData) {
    Customer::create($customerData);
}

echo "客户测试数据创建完成！\n";
echo "总共创建了 " . Customer::count() . " 条客户记录\n";
